### PR TITLE
Attack inspection

### PR DESCRIPTION
**Pull request by esarafianou**
Victim attack Inspection mockups with target configuration as a modal window

### CODE REVIEW

**Comment by dionyziz** [comment]
screenshot

**Comment by dionyziz** [comment]
Margin between Gmail icon and "Gmail" text too small on victim attack inspection page.

**Comment by dionyziz** [comment]
I don't think the "Victim Attack Inspection" header is necessary.

**Comment by dionyziz** [comment]
In victim attack inspection, IP and decrypted secrets are quite important. Make them a bit more prominent?

**Comment by dionyziz** [comment]
In victim attack inspection, Choose target and dropdown box are not vertically aligned with each other. Similar for IP textbox.

**Comment by dionyziz** [comment]
Model confirmation window is better written using action buttons.

Yes -> Delete
No -> Don't delete

It may be good to also color them appropriately. Delete = red. Don't delete = gray.

**Comment by esarafianou** [comment]
victiminspectionafter

**Comment by esarafianou** [comment]
victiminspectionbeforeip

**Comment by esarafianou** [comment]
victiminspectionbeforenoip

**Comment by esarafianou** [comment]
dropdown

**Comment by esarafianou** [comment]
deleteattackdetails

**Comment by esarafianou** [comment]
targetconf

**Comment by esarafianou** [comment]
after updates
screenshot from 2016-08-13 00-18-58

**Comment by esarafianou** [comment]
screenshot from 2016-08-13 00-18-43

**Comment by esarafianou** [comment]
screenshot from 2016-08-13 00-18-01

**Pull request merged**
